import React,{useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {Trash2} from "lucide-react";
import ViewerNav from "../../components/ViewerNav.jsx";
import {deleteRequest,getRequest} from "../../api/client.js";

export default function ViewerHistory(){const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const d=await getRequest("/viewer/history?limit=100");setItems(d.videos||[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]); async function clear(){if(!window.confirm("Clear your watch history?"))return;try{await deleteRequest("/viewer/history");setItems([])}catch(e){setError(e.message)}}
 return <div className="min-h-screen bg-[var(--stage)] text-[var(--parchment)]"><ViewerNav/><main className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="mb-8 flex items-end justify-between gap-4"><div><p className="font-[var(--font-mono)] text-[0.62rem] uppercase tracking-[0.14em] text-[var(--gold)]">Your record</p><h1 className="font-[var(--font-display)] text-4xl">Watch history</h1></div>{items.length>0&&<button onClick={clear} className="flex items-center gap-2 border border-[rgba(239,231,218,0.14)] px-3 py-2 font-[var(--font-mono)] text-[0.62rem] uppercase text-[var(--mauve)] hover:border-[var(--error)] hover:text-[var(--error)]"><Trash2 size={14}/>Clear</button>}</div>{error&&<div className="mb-5 rounded-[3px] border border-[rgba(224,138,107,.4)] px-4 py-3 text-sm text-[var(--error)]">{error}</div>}{loading?<p className="text-[var(--mauve)]">Loading history…</p>:items.length===0?<div className="border border-dashed border-[rgba(239,231,218,.16)] p-14 text-center"><h2 className="font-[var(--font-display)] text-2xl">No watch history yet.</h2><Link to="/viewer" className="mt-3 inline-block text-sm text-[var(--gold-soft)]">Discover a film</Link></div>:<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{items.map(v=><Link key={v.id} to={`/viewer/videos/${v.id}`} className="overflow-hidden rounded-[3px] border border-[rgba(239,231,218,.12)] bg-[#17131a] hover:border-[var(--gold)]"><img src={v.thumbnailUrl} alt={v.title} className="aspect-video w-full object-cover"/><div className="p-4"><h3 className="truncate font-[var(--font-display)] text-lg">{v.title}</h3><div className="mt-3 h-1 bg-white/10"><div className="h-full bg-[var(--gold)]" style={{width:`${Math.min(100,(v.progress||0)*100)}%`}}/></div><p className="mt-2 font-[var(--font-mono)] text-[0.58rem] uppercase text-[var(--mauve)]">{v.completed?"Completed":`${Math.round((v.progress||0)*100)}% watched`}</p></div></Link>)}</div>}</main></div>}
